### ISSUE TITLE
Can't push nor pull from repo

### ISSUE THREAD

**Issue by mcmiloy** [FUB-HCC/hcds-summer-2022#1]
push error:

remote: Permission to FUB-HCC/hcds-summer-2022.git denied to mcmiloy.
fatal: unable to access 'https://github.com/FUB-HCC/hcds-summer-2022.git/': The requested URL returned error: 403

pull error:
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 6 (delta 2), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (6/6), 819 bytes | 819.00 KiB/s, done.
From https://github.com/FUB-HCC/hcds-summer-2022
   fd95e4e..2ad95c0  main       -> origin/main
hint: You have divergent branches and need to specify how to reconcile them.
hint: You can do so by running one of the following commands sometime before
hint: your next pull:
hint: 
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint: 
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
fatal: Need to specify how to reconcile divergent branches.

github adds such a layer of complexity :(

**Comment by mcmiloy** [comment]
AH ok fixed the pull issue, maybe you just need to give us rights to push to main?  My university email is not my github email, so that might be the issue?
So you might have to give us access individually?

**Comment by portofaman** [comment]
I was able to push to `main`. Lars gave us access to the university email, but you can keep your actual github logged in to the browser and then accept the invitation which you must have received from Lars in your university email. This worked for me. :)

**Comment by mcmiloy** [comment]
Hmm I've doubled checked my university email but I don't think I got any link. Maybe Lars could post the invite on whiteboard instead?

**Comment by siposl** [comment]
Hey @mcmiloy, I gave you writing rights to this repository.

If anyone else is having trouble accessing this repository, please send an e-mail to: lars.sipos@fu-berlin.de.

Even if you have no writing rights, you are able to fork this repository and create a pull request.

I don't think that Github offers a mass invite link and even if it did, there are more people registered in Whiteboard than there are people who actively participate in this course.

**Comment by mcmiloy** [comment]
Cool thanks
